changelog:
  exclude:
    authors:
      - github-actions[bot]
  categories:
    - title: "🚀 核心变更 (PRs)"
      labels:
        - "*"
    - title: "📦 其它提交 (Commits)"
      collapse_after: 5
  include_direct_commits: true